name: "PPG"

#PPG specifics
N_pi: 32
E_pi: 1
E_v: 3
E_aux: 8
number_mb_per_epoch: 8
rollout_size: 512
aux_mb_per_N_pi: 16
beta_clone: 1.75
cost_loss_coef: 0.3

###architecture
a2c_architecture: "separate"
#if shared:
beta_reward: 0.5
beta_cost: 0.5

hidden_sizes: [256, 256]
activation: "tanh"
output_activation: "identity"
weight_initialization_method: "orthogonal"

###optimization
lr: 0.00005
anneal_lr: false
clip_epsilon: 0.2
entropy_coef: 0.00


###normalization
use_max_grad_norm: true
max_grad_norm: 2
normalize_adv_r: true
normalize_adv_c: true

###regularization
use_critic_norm: false
critic_norm_coef: 5000

###gae
gae:
  gamma: 0.99
  lam: 0.95

###early stopping
kl_early_stop: true
target_kl: 0.01

use_cost: false
cost_scaling: 1.0